name = "CitableArgumentation"
uuid = "33da99e0-ee0e-4e7b-b78c-54f681b188df"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.1.0"

[deps]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CommonMark = "0.8"
DocStringExtensions = "0.8"
Documenter = "0.27"
julia = "1"
